#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=IPK upload & install, file download and simple file management
LUCI_DEPENDS:=+luci-lib-fs
PKG_VERSION:=0.1.3
PKG_RELEASE:=1

#include $(TOPDIR)/feeds/luci/luci.mk
include ../../luci.mk
# call BuildPackage - OpenWrt buildroot signature
