# Copyright 2017-2020 guyezi (admin@guyezi.com)
# This is free software, licensed under the Apache License, Version 2.0

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-homebridge
LUCI_TITLE:=LuCI support for homebridge
LUCI_DEPENDS:=+node
LUCI_PKGARCH:=all
PKG_LICENSE_FILES:=LICENSE
PKG_LICENSE:=GPLv3

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
