#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.amazeui >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.amazeui=/luci-static/amazeui
		set luci.main.mediaurlbase=/luci-static/amazeui
		commit luci
	EOF
fi

exit 0
